[phases.setup]
nixPkgs = ['php83', 'php83Extensions.intl', 'php83Extensions.zip', 'php83Packages.composer', 'nodejs_20', 'npm-9_x']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev --no-scripts --no-interaction']

[phases.build]
cmds = ['npm ci && npm run build']

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
