[phases.setup]
nixPkgs = [
  'php83',
  'php83Extensions.intl',
  'php83Extensions.zip',
  'php83Extensions.pdo',
  'php83Extensions.pdo_mysql',
  'php83Extensions.mbstring',
  'php83Extensions.tokenizer',
  'php83Extensions.xml',
  'php83Extensions.ctype',
  'php83Extensions.fileinfo',
  'php83Extensions.bcmath',
  'php83Extensions.gd',
  'php83Packages.composer',
  'nodejs_20'
]

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev --no-scripts --no-interaction']

[phases.build]
cmds = ['npm ci && npm run build']
